language: r
cache: packages

r_packages:
  - covr
  - pkgdown

r:
  - release
  - devel

env:
  - RGL_USE_NULL=TRUE

r_binary_packages:
  - rgl

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

after_success:
  - Rscript -e 'library(covr);codecov()'
